### ISSUE TITLE
fix RSQLite bug where commas in fields are causing dbWriteTable to fail

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyc311#1]

**Comment by liwencong1995** [comment]
Should I try to get rid of the commas or should I keep them as part of the data? I couldn't find a way to fix this problem without reading the cvs file into the environment.

**Comment by liwencong1995** [comment]
If I do need to get rid of the commas, should I do it in etc_transform?

**Comment by beanumber** [comment]
Yes. You could try to read the CSV into R, then write it to a pipe-delimited file using write_delim().

**Comment by liwencong1995** [comment]
I specified "sep" as "%" as described in the link below. 
http://rpackages.ianhowson.com/cran/RSQLite/man/dbWriteTable.html

**Comment by beanumber** [comment]
Solved by writing file as pipe-delimited.
