### ISSUE TITLE
'valid_year_month' is not an exported object from 'namespace:etl' 

### ISSUE THREAD

**Issue by joelgombin** [beanumber/nyc311#13]
When I try to run the vignette example:

``` r
calls %>%
  etl_extract(years = 2010:2011, months = 1:2, num_calls = 100) %>%
  etl_transform(years = 2010:2011, months = 1:2) %>%
  etl_load(years = 2010:2011, months = 1:2)
```

I get this error: `'valid_year_month' is not an exported object from 'namespace:etl'`.

**Comment by beanumber** [comment]
This is the same issue as (https://github.com/beanumber/airlines/issues/50)
