### ISSUE TITLE
beta testing

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyc311#14]
@liwencong1995 is it time for some users to try and work with this package? Let's get this to a point where others can start beta testing it.

**Comment by liwencong1995** [comment]
@beanumber The ETL functions work well now, so it would be really nice if someone else can help to test the package!

**Comment by liwencong1995** [comment]
The only part breaks is the test!

**Comment by liwencong1995** [comment]
@brendamao @zixian97 @conniezyy and @czang97 will be helping with beta testing!

**Comment by conniezyy** [comment]
Chunk 45-48:
```{r}
calls <- etl("nyc311")
summary(calls)
```

Error:
Not a valid src. Creating a src_sqlite for you at:
/var/folders/dz/whyj60910y3cn2ht2vlxspl80000gn/T//Rtmp1dhxOU/file390943377035.sqlite3
Traceback:
Error: RSQLite package required to connect to sqlite db
5.
stop("RSQLite package required to connect to sqlite db", call. = FALSE)
4.
dplyr::src_sqlite(path = sqlite_file, create = TRUE)
3.
verify_con(db, dir)
2.
etl.default("nyc311")
1.
etl("nyc311")

**Comment by liwencong1995** [comment]
@beanumber Hi Ben, can you take a look at the error above? It seems that an etl object has been initialized, but the src_sqlite connection was not created in dir. I don't know how to fix it.

**Comment by crystalzang** [comment]
Actually I had the same problem creating "etl" object.
```{r}
calls <- etl("nyc311")
summary(calls)
```

Not a valid src. Creating a src_sqlite for you at:
/var/folders/6k/nrxhhtwx68s4kbpd8dp_b9xc0000gp/T//RtmpilkrbA/file17b56829023f.sqlite3
 Hide Traceback
Error: RSQLite package required to connect to sqlite db
5.
stop("RSQLite package required to connect to sqlite db", call. = FALSE)
4.
dplyr::src_sqlite(path = sqlite_file, create = TRUE)
3.
verify_con(db, dir)
2.
etl.default("nyc311")
1.
etl("nyc311")

**Comment by liwencong1995** [comment]
@conniezyy @czang97 Please try installing the R package `RSQLite` and run the command in `vignette` again. I think this problem occurred because `RSQLite` was not present in your system library.

**Comment by beanumber** [comment]
Yes, you need `RSQLite`!

**Comment by czang97** [comment]
1. After install the package "RSQLite", the same error shows up:
```{r}
calls <- etl("nyc311")
summary(calls)
```
Error:
Not a valid src. Creating a src_sqlite for you at:
/var/folders/6k/nrxhhtwx68s4kbpd8dp_b9xc0000gp/T//RtmpPESrNQ/fileba46e644b03.sqlite3

2. There is this error when I run the other chunks.
```{r}
if (require(leaflet)) { 
  leaflet(data = general_construction_location) %>% 
    addTiles() %>%
    addCircles()
}
```
Error:
Loading required package: leaflet
there is no package called 'leaflet'

**Comment by crystalzang** [comment]
Review: This package gives really sufficient information about nyc calls, shows interesting and useful facts related to the calls. The package runs smoothly with all the functions are written clearly.

**Comment by brendamao** [comment]
The package is very well written. I plugged in different years and months into the package and it still ran smoothly. The comments were especially helpful in terms of allowing the users to not only be able to run the code but also to understand the code.

**Comment by conniezyy** [comment]
After I installed RSQLite and etl, the package runs smoothly all the way to the end. Written in clear and concise language, this package features its great functionality and user-friendliness.
