### ISSUE TITLE
update etl_extract() to take "begin" and "end" date arguments

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyc311#2]

**Comment by beanumber** [comment]
if the column types are all correct, then `etl_transform` does nothing.

**Comment by beanumber** [comment]
On second thought, make `years` and `months` arguments like [airlines](http://www.github.com/beanumber/airlines).
- Create separate files for each month
- Use this idiom to compute last day of the month: `as.Date("2016-06-01") - 1`

**Comment by liwencong1995** [comment]
I do not know how to test whether a date is valid or not. I used the code that you suggested last week, but if the the user enters something like `year <- 12345`, the `as.Date` function will break. 

Also, it seems that `is.Date` only returns `TRUE` when I combine `is.Date` and `as.Date`. Therefore, I don't think `is.Date` is useful. Should we try something else? 

```
lubridate::is.Date(as.Date(paste0(year, "-", month, "-01")))
```

**Comment by beanumber** [comment]
I recommend checking the `year` and `month` parameters separately. So first check to see that `year` is between 2010 and the current year, and then separately check that `month` is an integer between 1 and 12. Then you can be sure that `as.Date` will return a valid date.
