### ISSUE TITLE
fix the 1000 rows limit when using download.file

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/nyc311#4]
https://confluence.atlassian.com/jirakb/export-more-than-1000-issues-to-excel-from-issue-navigator-in-jira-cloud-779160811.html

This might be a solution?

**Comment by beanumber** [comment]
Maybe. But what does Jira or Atlassian have to do with Socrataca?

**Comment by liwencong1995** [comment]
I found this link helpful! I will try to import all the rows by setting *fulldataset=true*.
https://github.com/drewgendreau/Socrata.jl

**Comment by beanumber** [comment]
solution is add `&limit=1000000` to get 1 million rows. That should suffice for now. 

Add an argument `n` for the number of rows, but set 1 million to be the default.

**Comment by liwencong1995** [comment]
I added a variable n, which could be set as any number between 0 and 1 million.
