### ISSUE TITLE
 build & reload Warning Message

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/nyc311#5]
I get this error msg every time I do build & reload:

Warning messages:
1: replacing previous import by ‘lubridate::intersect’ when loading ‘nyc311’ 
2: replacing previous import by ‘lubridate::union’ when loading ‘nyc311’ 
3: replacing previous import by ‘lubridate::setdiff’ when loading ‘nyc311’ 
4: package ‘lubridate’ was built under R version 3.2.4 
5: package ‘RCurl’ was built under R version 3.2.4

How can I solve it? Should I remove @import lubridate?

**Comment by beanumber** [comment]
You should probably use @importFrom for each lubridate function that you use instead of @import-ing the whole package.
