### ISSUE TITLE
investigate proper use of "na" argument to readr::write_delim

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyc311#9]
In the `raw` data, we have:
- `N/A`
- blank
  In the `load` data, we have:
- `N/A`
- blank
  Is that what we want? Should we convert the `N/A`'s to blanks? 
  In the data.frame that comes back into R from the SQL database, the raw `N/A`s stay as `N/A`s, but the blanks get mapped to `""` the empty string. Should they be `NA`s?

**Comment by beanumber** [comment]
Should we write `NULL` in the `load` data since we are always going to load this directly into SQL? This will result in larger file sizes.

**Comment by liwencong1995** [comment]
When I changed the empty string into "NULL", R rewrites all the "NA"s as "Null"s.

```
readr::write_delim(datafile, path = valid_months$new_lcl[i], delim = "|", na = "NULL")

> calls %>%
+   etl_extract(years = 2010:2011, months = 1:3, n =100) %>%
+   etl_transform(years = 2010:2011, months = 1:3) %>%
+   etl_load(years = 2010:2011, months = 1:3)

> calls <- calls %>%
+   tbl("calls") %>%
+   collect()
> View(calls)
> calls$bridge_highway_segment
 [1] "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL"
 [11] "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL"
 [21] "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL" "NULL"
```

**Comment by beanumber** [comment]
Right. So then what do they look like when you get the data back from SQLite?

**Comment by liwencong1995** [comment]
When I ran `etl`, I did not specify my `db`. Therefore, the result above is what I got from SQLite.
